version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.12"
    nodejs: "20"
    # rust: "1.55"
    # golang: "1.17"
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - requirements: docs/requirements.txt
